export const colors = {
  bg: '#F4F6F8',
  card: '#FFFFFF',
  text: '#16212B',
  subtext: '#5B6B7A',
  border: '#E3E8EE',
  primary: '#2563EB',
  primarySoft: '#DBEAFE',
  white: '#FFFFFF',
  green: '#16A34A',
  greenSoft: '#DCFCE7',
  amber: '#B45309',
  amberSoft: '#FEF3C7',
  orange: '#C2410C',
  orangeSoft: '#FFEDD5',
  red: '#DC2626',
  redSoft: '#FEE2E2',
  slate: '#64748B',
  slateSoft: '#E2E8F0',
}

export type Tone = { fg: string; bg: string }

const tones = {
  green: { fg: colors.green, bg: colors.greenSoft },
  amber: { fg: colors.amber, bg: colors.amberSoft },
  orange: { fg: colors.orange, bg: colors.orangeSoft },
  red: { fg: colors.red, bg: colors.redSoft },
  slate: { fg: colors.slate, bg: colors.slateSoft },
  blue: { fg: colors.primary, bg: colors.primarySoft },
} satisfies Record<string, Tone>

export const statusTone: Record<string, Tone> = {
  PAID: tones.green,
  PARTIAL: tones.amber,
  UNPAID: tones.orange,
  LATE: tones.red,
  UPCOMING: tones.slate,
  NO_CHARGES: tones.slate,
  OPEN: tones.orange,
  IN_PROGRESS: tones.amber,
  RESOLVED: tones.green,
  ACTIVE: tones.green,
  MONTH_TO_MONTH: tones.blue,
  ENDED: tones.slate,
  FORMER: tones.slate,
  VACANT: tones.slate,
  OCCUPIED: tones.green,
  LOW: tones.slate,
  NORMAL: tones.blue,
  HIGH: tones.orange,
  URGENT: tones.red,
}

export const statusLabel: Record<string, string> = {
  PAID: 'Paid',
  PARTIAL: 'Partial',
  UNPAID: 'Unpaid',
  LATE: 'Late',
  UPCOMING: 'Upcoming',
  NO_CHARGES: 'No charges',
  OPEN: 'Open',
  IN_PROGRESS: 'In progress',
  RESOLVED: 'Resolved',
  ACTIVE: 'Active',
  MONTH_TO_MONTH: 'Month-to-month',
  ENDED: 'Ended',
  FORMER: 'Former',
  VACANT: 'Vacant',
  OCCUPIED: 'Occupied',
  LOW: 'Low',
  NORMAL: 'Normal',
  HIGH: 'High',
  URGENT: 'Urgent',
}
